use `system`;

-- 系统代码
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10001-10004', null, 'zh_CN', '10004', '性别', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10001-10005', null, 'zh_CN', '10005', '婚姻状况', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10001-10006', null, 'zh_CN', '10006', '学历', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10001-10027', null, 'zh_CN', '10027', '机构类型', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10001-10042', null, 'zh_CN', '10042', '消息类型', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10001-10068', null, 'zh_CN', '10068', '附件类型', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10001-10078', null, 'zh_CN', '10078', '日志操作类型', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10001-10079', null, 'zh_CN', '10079', '权限分配类型', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10001-10080', null, 'zh_CN', '10080', '职级', 1, 1, now(), 0);

insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10004-10', '10001-10004', 'zh_CN', '10', '男', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10004-20', '10001-10004', 'zh_CN', '20', '女', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10005-10', '10001-10005', 'zh_CN', '10', '已婚', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10005-20', '10001-10005', 'zh_CN', '20', '未婚', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10006-10', '10001-10006', 'zh_CN', '10', '本科', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10006-20', '10001-10006', 'zh_CN', '20', '研究生', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10006-30', '10001-10006', 'zh_CN', '30', '硕士', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10006-40', '10001-10006', 'zh_CN', '40', '博士', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10027-10', '10001-10027', 'zh_CN', '10', '部门', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10027-20', '10001-10027', 'zh_CN', '20', '公司/往来单位', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10027-30', '10001-10027', 'zh_CN', '30', '机构/单位', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10042-10', '10001-10042', 'zh_CN', '10', '系统消息', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10068-70', '10001-10068', 'zh_CN', '70', '头像', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10078-10', '10001-10078', 'zh_CN', '10', '登录', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10078-20', '10001-10078', 'zh_CN', '20', '退出', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10079-10', '10001-10079', 'zh_CN', '10', '部门', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10079-20', '10001-10079', 'zh_CN', '20', '职位', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10079-30', '10001-10079', 'zh_CN', '30', '角色', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10079-40', '10001-10079', 'zh_CN', '40', '人员', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-10', '10001-10080', 'zh_CN', '10', '厅长', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-100', '10001-10080', 'zh_CN', '100',  '四级调研员', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-110', '10001-10080', 'zh_CN', '110', '一级主任科员', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-120', '10001-10080', 'zh_CN', '120', '二级主任科员', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-130', '10001-10080', 'zh_CN', '130', '三级主任科员', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-140', '10001-10080', 'zh_CN', '140', '四级主任科员', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-150', '10001-10080', 'zh_CN', '150', '督办', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-160', '10001-10080', 'zh_CN', '160', '一级高级主办', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-170', '10001-10080', 'zh_CN', '170', '二级高级主办', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-180', '10001-10080', 'zh_CN', '180', '三级高级主办', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-190', '10001-10080', 'zh_CN', '190', '四级高级主办', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-20', '10001-10080', 'zh_CN', '20', '局长', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-200', '10001-10080', 'zh_CN', '200', '一级主办', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-210', '10001-10080', 'zh_CN', '210', '二级主办', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-220', '10001-10080', 'zh_CN', '220', '三级主办', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-230', '10001-10080', 'zh_CN', '230', '四级主办', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-240', '10001-10080', 'zh_CN', '240', '一级行政执法员', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-250', '10001-10080', 'zh_CN', '250', '领导管理五级', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-260', '10001-10080', 'zh_CN', '260', '领导管理六级', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-270', '10001-10080', 'zh_CN', '270', '普通管理八级', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-280', '10001-10080', 'zh_CN', '280', '专技十三级', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-290', '10001-10080', 'zh_CN', '290', '专技十二级', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-30', '10001-10080',  'zh_CN', '30', '所长', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-300', '10001-10080', 'zh_CN', '300', '专技十一级', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-310', '10001-10080', 'zh_CN', '310', '专技十级',  1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-320', '10001-10080', 'zh_CN', '320', '专技九级',  1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-330', '10001-10080', 'zh_CN', '330', '专技八级',  1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-340', '10001-10080', 'zh_CN', '340', '专技七级',  1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-350', '10001-10080', 'zh_CN', '350', '专技六级',  1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-360', '10001-10080', 'zh_CN', '360', '专技五级',  1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-370', '10001-10080', 'zh_CN', '370', '专技三级',  1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-380', '10001-10080', 'zh_CN', '380', '专技见习期', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-390', '10001-10080', 'zh_CN', '390', '技术工五级', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-40', '10001-10080', 'zh_CN', '40', '科长', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-50', '10001-10080', 'zh_CN', '50', '一级巡视员', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-60', '10001-10080', 'zh_CN', '60', '二级巡视员', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-70', '10001-10080', 'zh_CN', '70', '一级调研员', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-80', '10001-10080', 'zh_CN', '80', '二级调研员', 1, 1, now(), 0);
insert into `system`.`t_sys_code` (`value`, type, locale, code, name, is_sys, create_by, create_time, is_deleted) values ('10080-90', '10001-10080', 'zh_CN', '90', '三级调研员', 1, 1, now(), 0);




INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'flow_define_history', '历史流程定义', 'processDefineName', '流程定义名称', 1, 1, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'flow_define_history', '历史流程定义', 'version', '版本号', 1, 2, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'flow_define_history', '历史流程定义', 'category', '流程分类', 1, 3, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'flow_define_history', '历史流程定义', 'key', '模型表示', 1, 4, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'flow_define_history', '历史流程定义', 'processDefineId', '流程定义Id', 1, 5, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'flow_define_list', '流程定义管理', 'orgName', '机关(单位)', 1, 1, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'flow_define_list', '流程定义管理', 'bizName', '流程名称', 1, 2, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'flow_define_list', '流程定义管理', 'bizType', '类型', 1, 3, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'flow_define_list', '流程定义管理', 'defineId', '流程id', 1, 4, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'flow_define_list', '流程定义管理', 'createBy', '创建人', 1, 5, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'flow_define_list', '流程定义管理', 'createTime', '创建时间', 1, 6, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'flow_instance_list', '流程实例管理', 'orgName', '机关(单位)', 1, 1, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'flow_instance_list', '流程实例管理', 'bizType', '类型', 1, 2, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'flow_instance_list', '流程实例管理', 'title', '标题', 1, 3, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'flow_instance_list', '流程实例管理', 'taskDefineKey', '当前任务节点', 1, 4, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'flow_instance_list', '流程定义管理', 'createTime', '申请时间', 1, 5, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'flow_instance_list', '流程定义管理', 'completeTime', '完成时间', 1, 6, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'flow_instance_list', '流程实例管理', 'status', '状态', 1, 7, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'flow_model_list', '模型管理', 'category', '分类', 1, 1, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'flow_model_list', '模型管理', 'name', '名称', 1, 2, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'flow_model_list', '模型管理', 'key', '关键字', 1, 3, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'flow_model_list', '模型管理', 'revision', '版本号', 1, 4, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'flow_model_list', '模型管理', 'createTime', '创建时间', 1, 5, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'flow_model_list', '模型管理', 'lastUpdateTime', '最后更新时间', 1, 6, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'sys_code_list', '系统代码', 'name', '名称', 1, 1, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'sys_code_list', '系统代码', 'code', '代码', 1, 2, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'sys_code_list', '系统代码', 'type', '类别', 1, 3, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'sys_code_list', '系统代码', 'value', '代码值', 1, 4, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'sys_code_list', '系统代码', 'isSys', '系统/用户', 1, 6, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'sys_operation_log_list', '操作日志', 'targetServer', '服务实例', 1, 1, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'sys_operation_log_list', '操作日志', 'requestPath', '资源路径', 1, 2, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'sys_operation_log_list', '操作日志', 'ip', 'IP地址', 1, 3, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'sys_operation_log_list', '操作日志', 'userName', '操作人', 1, 4, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'sys_operation_log_list', '操作日志', 'opTime', '操作时间', 1, 5, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'sys_operation_log_list', '操作日志', 'operation', '操作', 1, 6, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'sys_project_list', '应用管理', 'name', '名称', 1, 6, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'sys_project_list', '应用管理', 'code', '代码', 1, 6, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'sys_project_list', '应用管理', 'orderNo', '排序号', 1, 6, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_dept_person_list', '部门调整', 'orgName', '机关（单位）', 0, 1, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_dept_person_list', '部门调整', 'deptName', '部门', 1, 2, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_dept_person_list', '部门调整', 'personName', '人员', 1, 3, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_dept_person_list', '部门调整', 'posName', '职位', 1, 4, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_dept_person_list', '部门调整', 'orderNo', '顺序号', 1, 5, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_function_list', '菜单管理', 'parent', '上级菜单', 1, 1, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_function_list', '菜单管理', 'name', '名称', 1, 2, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_function_list', '菜单管理', 'code', '代码', 1, 3, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_function_list', '菜单管理', 'action', '地址', 1, 4, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_function_list', '菜单管理', 'imgPath', '图标路径', 1, 5, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_function_list', '菜单管理', 'orderNo', '排序号', 1, 6, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_login_log_list', '登录日志', 'type', '事件类型', 1, 1, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_login_log_list', '登录日志', 'opContent', '内容', 1, 2, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_login_log_list', '登录日志', 'ip', 'IP地址', 1, 3, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_login_log_list', '登录日志', 'time', '操作时间', 1, 4, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_login_log_list', '登录日志', 'orgName', '机关(单位)', 1, 5, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_org_list', '部门管理', 'orgName', '机关（单位）', 0, 1, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_org_list', '部门管理', 'name', '名称', 1, 2, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_org_list', '部门管理', 'code', '代码', 1, 3, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_org_list', '部门管理', 'shortName', '简称', 1, 4, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_org_list', '部门管理', 'contactPerson', '联系人', 1, 5, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_org_list', '部门管理', 'orderNo', '顺序号', 1, 6, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_person_list', '人员管理', 'orgName', '机关（单位）', 0, 1, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_person_list', '人员管理', 'personName', '姓名', 1, 2, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_person_list', '人员管理', 'account', '账号', 1, 3, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_person_list', '人员管理', 'sex', '性别', 1, 4, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_person_list', '人员管理', 'mobile', '手机', 1, 5, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_person_list', '人员管理', 'personDept', '部门', 1, 6, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_person_list', '人员管理', 'roles', '角色', 1, 8, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_person_list', '人员管理', 'createTime', '创建时间', 1, 9, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_position_list', '职位管理', 'orgName', '机关（单位）', 0, 1, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_position_list', '职位管理', 'name', '名称', 1, 2, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_position_list', '职位管理', 'code', '代码', 1, 3, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_position_list', '职位管理', 'type', '职位类型', 1, 4, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_position_list', '职位管理', 'createBy', '创建人', 1, 5, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_position_list', '职位管理', 'createTime', '创建时间', 1, 6, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_role_list', '角色管理', 'orgName', '机关（单位）', 0, 1, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_role_list', '角色管理', 'name', '名称', 1, 2, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_role_list', '角色管理', 'code', '代码', 1, 3, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_role_list', '角色管理', 'isSys', '系统/用户', 1, 4, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_role_list', '角色管理', 'createBy', '创建人', 1, 5, 0);
INSERT INTO `system`.`t_sys_column_config` (user_id, code, name, col_key, col_name, is_selected, order_no, is_deleted) VALUES (0, 'ucenter_role_list', '角色管理', 'createTime', '创建时间', 1, 6, 0);


-- 系统模块
insert into `system`.`t_sys_project` (name, code, order_no, create_by, create_time, is_deleted) VALUES ('系统管理', 'ucenter', 100, 1, now(), 0);

-- 菜单
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (100000, '基础数据', null, null, 'base_module', 1, 'system', 100000, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (101000, '人员管理', '/ucenterPerson/list', 100000, 'ucenter_person_list', 2, null, 101000, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (101010, '新增', '/ucenterPerson/add', 101000, 'ucenter_person_add', 4, null, 101010, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (101020, '编辑', '/ucenterPerson/save', 101000, 'ucenter_person_edit', 4, null, 101020, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (101030, '删除', '/ucenterPerson/delete', 101000, 'ucenter_person_delete', 4, null, 101030, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (101040, '查看', '/ucenterPerson/view', 101000, 'ucenter_person_view', 4, null, 101040, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (101050, '重置密码', '/ucenterPerson/resetPwd', 101000, 'ucenter_person_password_reset', 4, null, 101050, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (101060, '锁定', '/ucenterPerson/lock', 101000, 'ucenter_person_account_frozen', 4, null, 101060, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (101070, '解锁', '/ucenterPerson/unlock', 101000, 'ucenter_person_account_unfrozen', 4, null, 101070, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (101080, '注销', '/ucenterPerson/destroy', 101000, 'ucenter_person_account_cancel', 4, null, 101080, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (103000, '部门管理', '/ucenterOrg/list', 100000, 'ucenter_org_list', 2, null, 103000, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (103010, '新增', '/ucenterOrg/add', 103000, 'ucenter_org_add', 4, null, 103010, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (103020, '查看', '/ucenterOrg/view', 103000, 'ucenter_org_view', 4, null, 103020, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (103030, '编辑', '/ucenterOrg/save', 103000, 'ucenter_org_edit', 4, null, 103030, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (103040, '删除', '/ucenterOrg/delete', 103000, 'ucenter_org_delete', 4, null, 103040, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (104000, '部门调整', '/ucenterDeptPerson/list', 100000, 'ucenter_dept_person_list', 2, null, 104000, 1, 1, now(), 1);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (104010, '调整', '/ucenterDeptPerson/add', 104000, 'ucenter_dept_person_add', 4, null, 104010, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (104020, '查看', '/ucenterDeptPerson/view', 104000, 'ucenter_dept_person_view', 4, null, 104020, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (105000, '权限管理', '/ucenterObjFunc/list', 100000, 'ucenter_obj_func_list', 2, null, 105000, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (105010, '新增', '/ucenterObjFunc/save', 105000, 'ucenter_obj_func_save', 4, null, 105010, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (107000, '职务管理', '/ucenterPosition/list', 100000, 'ucenter_position_list', 2, null, 107000, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (107010, '新增', '/ucenterPosition/add', 107000, 'ucenter_position_add', 4, null, 107010, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (107020, '编辑', '/ucenterPosition/save', 107000, 'ucenter_position_edit', 4, null, 107020, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (107030, '删除', '/ucenterPosition/delete', 107000, 'ucenter_position_delete', 4, null, 107030, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (107040, '查看', '/ucenterPosition/view', 107000, 'ucenter_position_view', 4, null, 107040, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (108000, '角色管理', '/ucenterRole/list', 100000, 'ucenter_role_list', 2, null, 108000, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (108010, '新增', '/ucenterRole/add', 108000, 'ucenter_role_add', 4, null, 108010, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (108020, '编辑', '/ucenterRole/save', 108000, 'ucenter_role_edit', 4, null, 108020, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (108030, '删除', '/ucenterRole/delete', 108000, 'ucenter_role_delete', 4, null, 108030, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (108040, '查看', '/ucenterRole/view', 108000, 'ucenter_role_view', 4, null, 108040, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (200000, '系统配置', null, null, 'system_module', 1, 'unit', 200000, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (201000, '系统代码', '/sysCode/list', 200000, 'sys_code_list', 2, null, 201000, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (201010, '新增', '/sysCode/add', 201000, 'sys_code_add', 4, null, 201010, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (201020, '编辑', '/sysCode/save', 201000, 'sys_code_edit', 4, null, 201020, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (201030, '删除', '/sysCode/delete', 201000, 'sys_code_delete', 4, null, 201030, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (201040, '查看', '/sysCode/view', 201000, 'sys_code_view', 4, null, 201040, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (201500, '日志管理', null, 200000, 'ucenter_log_list', 2, null, 201500, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (201510, '登录日志', '/ucenterLog/list', 201500, 'ucenter_login_log_list', 3, null, 201510, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (201520, '操作日志', '/sysOperationLog/list', 201500, 'sys_operation_log_list', 3, null, 201520, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (201600, '系统参数设置', '/sysParameter/list', 200000, 'sys_parameter_list', 2, null, 201600, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (201610, '保存', '/sysParameter/save', 201600, 'sys_parameter_save', 4, null, 201610, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (204000, '菜单管理', '/sysFunction/list', 200000, 'ucenter_function_list', 2, null, 204000, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (204010, '新增', '/sysFunction/add', 204000, 'ucenter_function_add', 4, null, 204010, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (204020, '编辑', '/sysFunction/save', 204000, 'ucenter_function_edit', 4, null, 204020, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (204030, '删除', '/sysFunction/delete', 204000, 'ucenter_function_delete', 4, null, 204030, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (204040, '查看', '/sysFunction/view', 204000, 'ucenter_function_view', 4, null, 204040, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (205000, '应用管理', '/sysProject/list', 200000, 'sys_project_list', 2, null, 205000, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (205010, '新增', '/sysProject/add', 205000, 'sys_project_add', 4, null, 205010, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (205020, '编辑', '/sysProject/save', 205000, 'sys_project_save', 4, null, 205020, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (205030, '删除', '/sysProject/delete', 205000, 'sys_project_delete', 4, null, 205030, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (205040, '查看', '/sysProject/view', 205000, 'sys_project_view', 4, null, 205030, 1, 1, now(), 0);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (206000, '流程管理', null, 200000, 'flow_manager', 2, null, 206000, 1, 1, now(), 1);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (206010, '模型管理', '/flowModel/list', 206000, 'flow_model_list', 2, null, 206010, 1, 1, now(), 1);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (206020, '新增', '/model/add', 206010, 'flow_model_add', 4, null, 206020, 1, 1, now(), 1);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (206030, '编辑', '/model/save', 206010, 'flow_model_save', 4, null, 206030, 1, 1, now(), 1);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (206040, '删除', '/model/delete', 206010, 'flow_model_delete', 4, null, 206040, 1, 1, now(), 1);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (206050, '在线设计', null, 206010, 'flow_model_edit', 4, null, 206050, 1, 1, now(), 1);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (206060, '部署', '/model/deploy', 206010, 'flow_model_deploy', 4, null, 206060, 1, 1, now(), 1);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (206200, '流程定义管理', null, 206000, 'flow_define_manager', 2, null, 206200, 1, 1, now(), 1);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (206210, '流程定义', '/oaFlowDefine/list', 206200, 'flow_define_list', 3, null, 206210, 1, 1, now(), 1);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (206211, '新增', '/oaFlowDefine/add', 206210, 'oa_flow_define_add', 4, null, 206211, 1, 1, now(), 1);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (206212, '编辑', '/oaFlowDefine/save', 206210, 'oa_flow_define_edit', 4, null, 206212, 1, 1, now(), 1);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (206213, '删除', '/oaFlowDefine/delete', 206210, 'oa_flow_define_delete', 4, null, 206213, 1, 1, now(), 1);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (206214, '查看', '/oaFlowDefine/view', 206210, 'oa_flow_define_view', 4, null, 206214, 1, 1, now(), 1);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (206220, '历史流程定义', '/define/page', 206200, 'flow_define_history', 3, null, 206220, 1, 1, now(), 1);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (206230, '删除', '/define/delete', 206200, 'flow_define_delete', 4, null, 206230, 1, 1, now(), 1);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (206300, '流程实例管理', '/oaFlow/list', 206000, 'oa_flow_query', 2, null, 206300, 1, 1, now(), 1);
insert into `system`.`t_sys_function` (id, name, action, parent_id, code, type, img_path, order_no, project_id, create_by, create_time, is_deleted) values (206310, '作废', '/task/stop', 206300, 'flow_instance_stop', 4, null, 206310, 1, 1, now(), 1);

commit;