export const btnConfigs = [
    {
        type: "add",
        text: "新增",
        icon: "el-icon-aliadd",
        has: "ucenter_person_add",
        handlerType: "handleAddClick",
    },
    {
        type: "modify",
        text: "修改",
        icon: "el-icon-alimodify",
        has: "ucenter_person_edit",
        handlerType: "handleEditClick",
    },
    {
        type: "remove",
        text: "删除",
        icon: "el-icon-aliback",
        has: "ucenter_person_delete",
        handlerType: "handleDeleteClick",
    },
    {
        type: "remove",
        text: "锁定",
        icon: "el-icon-alifreeze",
        has: "ucenter_person_account_frozen",
        handlerType: "handleLockClick",
    },
    {
        type: "remove",
        text: "解锁",
        icon: "el-icon-aliunfreeze",
        has: "ucenter_person_account_unfrozen",
        handlerType: "handleUnLockClick",
    },
    {
        type: "remove",
        text: "注销",
        icon: "el-icon-alilogoff",
        has: "ucenter_person_account_cancel",
        handlerType: "handleDestroyClick",
    },
    {
        type: "remove",
        text: "重置密码",
        icon: "el-icon-alipswreset",
        has: "ucenter_person_password_reset",
        handlerType: "handleResetPwdClick",
    },
    {
        type: "refresh",
        text: "刷新",
        icon: "el-icon-alirefresh",
        handlerType: "getTableList",
    },
];
export const searchFormConfig = [
    {
        type: "input",
        label: "姓名",
        prop: "nameQueryLike",
    },
    {
        type: "select",
        label: "性别",
        prop: "sex",
        children: [],
    },
    {
        type: "select",
        label: "婚姻状况",
        prop: "marriage",
        children: [],
        url:"getUcenterCodeCombox",
        params:{type:'10001-10005'},
    },
    {
        type: "select",
        label: "学历",
        prop: "education",
        children: [],
        url:"getUcenterCodeCombox",
        params:{type:'10001-10006'}
    },
    {
        type: "select",
        label: "职务",
        prop: "posId",
        normalizer: {
            label: "name",
            value: "id",
        },
        children: [],
    },
    {
        type: "select",
        label: "角色",
        prop: "roleIdQuery",
        normalizer: {
            label: "name",
            value: "id",
        },
        children: [],
    },
    {
        type: "slot",
        label: "",
        slotName: "slot-botton",
    },
];
export const titList = [
    {
        colKey: "orgName",
        prop: "orgName",
        label: "机关（单位）",
        width: null,
    },
    {
        colKey: "personName",
        prop: "name",
        label: "姓名",
        minWidth: 30,
        orderBy: "name",
        asc: "",
        type: "click",
        isOperation: true,
    },
    {
        colKey: "account",
        prop: "account",
        label: "账号",
        minWidth: 40,
        orderBy: "account",
        asc: "",
        type: "isSlot",
        slotName: "account",
    },
    {
        colKey: "sex",
        prop: "sexName",
        label: "性别",
        minWidth: 22,
    },
    {
        colKey: "mobile",
        prop: "mobile",
        label: "手机",
        minWidth: 35,
    },
    {
        colKey: "personDept",
        prop: "deptNames",
        label: "部门",
        minWidth: 30,
    },
    {
        colKey: "position",
        prop: "posName",
        label: "职位",
        minWidth: 30,
    },
    {
        colKey: "roles",
        prop: "roleNames",
        label: "角色",
        minWidth: 30,
    },
    {
        colKey: "createTime",
        prop: "createTime",
        label: "创建时间",
        minWidth: 50,
        orderBy: "createTime",
        asc: "",
    },
]
